# Generated by Django 4.0.5 on 2022-06-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='familia_nava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('parentesco', models.CharField(max_length=20)),
                ('nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Familia',
        ),
    ]
